# frozen_string_literal: true

source "https://rubygems.org"

gem "rails"
gem "pry"
gem "nokogiri"
gem 'sinatra'
gem 'thin'
gem 'require_all'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'rake'
gem 'sqlite3'
gem "capistrano"